### ISSUE TITLE
Only folders available in container(shared directory)

### ISSUE THREAD

**Issue by ellonde** [alrojo/tensorflow-tutorial#1]
I have cloned the repository to C:\Users\Mathias\Desktop\Docker so that i have C:\Users\Mathias\Desktop\Docker\tensorflow_tutorial\download-and-setup and so on.
if I run the following command:
docker run -p 8888:8888 -v C:\Users\Mathias\Desktop\Docker\tensorflow_tutorial:/mnt/myproject -it alrojo/tf-sklearn-cpu
I have a folder named tensorflow_tutorial within /mnt/myproject/ but no files.
If i change the folder for sharing i can see subdirectories but not still not the content of these.
I feel like the point of a shared directory is to be able to share files?

**Comment by alrojo** [comment]
I assume you are running a windows operating system.

Try typing `pwd` in your docker command line. You will find that docker does not use windows style path formatting so `C:\Users\Mathias\Desktop\Docker\tensorflow_tutorial` is not a legitimate path.

**Comment by ellonde** [comment]
Yes i am. Then what would be the legitimate path for that folder? 
Maybe im an idiot, but I cant get it working, i feel like i have tried any version or possible way of specifying the path.

For now i have just used docker cp to copy the files into the container.

**Comment by alrojo** [comment]
We had a lot of issues with windows and docker for this lab.
If `docker cp` works for you then great.

Else, I think the path would be something like `/c/Users/...`, but docker might complain given the absolute path.
Instead, some had luck with providing the path from the `$HOME` directory using `~`.

Try typing `cd ~/`, this will leave you in your home directory, from here you can specify the relative path to your directory with the `tensorflow_tutorial` folder.
I.e. `-v ~/deep_learning_courses/tensorflow_tutorial:/mnt/myproject`

**Comment by Carmezim** [comment]
@ellonde If you didn't try going to your directory through the docker WIndows console and typing pwd, just try that as it will print you the path you need to use as alrojo mentioned, e.g.:
`c/Users/Mathias/Desktop/Docker/tensorflow_tutorial/
`

Then on docker terminal:

```
docker run -p 8888:8888 -v /c/Users/Mathias/Desktop/tensorflow-tutorial:
/mnt/myproject -it alrojo/tf-sklearn-cpu
```

I tried it on a machine running Windows 10 and worked following the instructions. In my case specifically, I used: `/c/Users/<username>/tensorflow-tutorial-master:/mnt/myproject`

edit: docker terminal

**Comment by ellonde** [comment]
In the windows console i cant do pwd, but cd just gives the path standard windows path syntax. I think ill just ask for help on monday, I have spent too much time on this now :( But thank for the help :)

**Comment by Carmezim** [comment]
This is strange though, you were supposed to be able to use pwd, anyways, the only difference is that it is going to give you the path like this:
 `c/Users/Mathias/Desktop/Docker/tensorflow_tutorial/` 
with forward slashes and without colon, 

instead of the standard path as:
`C:\Users\Mathias\Desktop\Docker\tensorflow_tutorial`

So just replace it (or maybe copy and paste the example above on docker) and if just that was the problem it may work.

**Comment by ellonde** [comment]
isnt pwd a linux command?
If i run the following a container is started but i dont see any file sharing. But there is nothing in mnt/myproject and if i make a file there it doesn't appear in windows:
`docker run -p 8888:8888 -v /c/Users/Mathias/Desktop/Docker/tensorflow_tutorial/:/mnt/myproject -it alrojo/tf-sklearn-cpu`

**Comment by Carmezim** [comment]
Sorry, I mean in the docker command terminal.

The only different thing I did than you was to download the files instead of cloning the repository but this will be the same.  Sorry not offering more help, I hope you get it going.

**Comment by alrojo** [comment]
Closing this issue.
