### ISSUE TITLE
Lab4 Kaggle - argument typo

### ISSUE THREAD

**Issue by LecJackS** [alrojo/tensorflow-tutorial#2]
In lab4 "Build the model", convolutional2d is called as

```
# wrapping conv with batch_norm
def conv(l_in, num_outputs, kernel_size, scope, stride=1):
    return convolution2d(l_in, num_outputs=num_outputs, kernel_size=kernel_size,
                         stride=stride, normalize_fn=batch_norm, scope=scope)
```

Which produces:

> TypeError: convolution2d() got an unexpected keyword argument 'normalize_fn'

It should be "normalize**r**_fn". Adding that missing R makes it works perfectly.

**Comment by alrojo** [comment]
Thank for noticing @LecJackS !

Fixed in this [commit](https://github.com/alrojo/tensorflow-tutorial/commit/dd7342a2ceff298985d36bac547b985f116aebe2).
